### PR TITLE
Default location of smcl should be the old location

### PR DESCRIPTION
**Pull request by v1kko**
simple change to maintain old behaviour, if the new behaviour is correct, then tests/driver.sh should be updated instead

### CODE REVIEW

**Comment by v1kko** [comment]
Also updated the python3 version of f2c_alpha, perhaps it is best to only maintain (and include) only one version to prevent divergence between the two versions

**Comment by theoc** [comment]
> Also updated the python3 version of f2c_alpha, perhaps it is best to only maintain (and include) only one version to prevent divergence between the two versions

This is the plan. For the time being (until the next release of EMAC) we'd like to maintain both while users adapt their environments/workflows.

> simple change to maintain old behaviour, if the new behaviour is correct, then tests/driver.sh should be updated instead

The new behaviour is desired by the EMAC maintainers, so perhaps best to simply update `tests/driver.sh`

**Review by theoc — CHANGES_REQUESTED** [review]
The new behaviour is desired by the EMAC maintainers, so perhaps best to simply update `tests/driver.sh`

**Comment by v1kko** [comment]
I added the requested changes, f2c_alpha now has an option [-s,--smcl] to set the smcl directory.
- the default is ../../smcl/
- tests/driver.sh sets this to ../smcl/

**Review by theoc — APPROVED** [review]

**Pull request merged**
